include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # ✅ Widget performance
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    unnecessary_const: true

    # ✅ Async & Stream performance
    unawaited_futures: true
    avoid_returning_null_for_future: true
    avoid_void_async: true

    # ✅ Common performance patterns
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    prefer_final_locals: true
    prefer_final_in_for_each: true

    # ✅ Code cleanliness (indirectly helps performance)
    avoid_print: true
    always_use_package_imports: true
    no_duplicate_case_values: true

    # ✅ Memory leaks & rebuild issues
    use_key_in_widget_constructors: true
    avoid_redundant_argument_values: true
    avoid_init_to_null: true

    # ✅ Dart null safety & strict typing
    avoid_types_on_closure_parameters: false # optionally true

analyzer:
  exclude:
    - "**/*.g.dart"
