name: infinialabs_ai
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  get: ^4.7.2
  curl_logger_dio_interceptor: ^1.0.0
  provider: ^6.1.4
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  shared_preferences: ^2.5.3
  basic_utils: ^5.8.2
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  build_runner: ^2.1.11

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash.jpg"
  android: true
  ios: false

  android_12:
    image: "assets/images/splash.jpg"